name: Unit tests

on: [push]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    name: ${{ matrix.os }} python ${{ matrix.python-version }} test
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
    - name: Show environment info
      run: |
        which python
        which conda
        conda env list
        conda list

    - name: Test with pytest
      run: |
        conda activate base && conda install pytest && pytest tests