name: Guertena working

on: [push]

jobs:
  test-environment:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    name: ${{ matrix.os }} python ${{ matrix.python-version }} test
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
    - name: Test with pytest
      run: |
        conda install pytest && pytest tests